name: workflow for push and pull request

on:
  push:
    branches:
      - main
      - "feat/**"

    paths:
      - "src/**"

  pull_request:
    branches:
      - main
      - "feat/**"

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:

    - name: checkout repo
      uses: actions/checkout@v5

    - name: print message
      run: echo "push or pull request was run successfully!"


